sudo: required
services:
  - docker

before_install:
  - docker build -t mmorency/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true mmorency/docker-react npm run test

langauage: generic